import React from "react";
import "./reports.css";

function Reports({ user, onBack }) {

  const reports = [
    {
      title: "Solar Potential Analysis",
      location: "Visakhapatnam",
      type: "Solar",
      score: "77.6%",
      date: "15 Aug 2026",
    },
    {
      title: "Wind Energy Assessment",
      location: "Vizag",
      type: "Wind",
      score: "72.4%",
      date: "14 Aug 2026",
    },
    {
      title: "Renewable Site Selection",
      location: "Andhra Pradesh",
      type: "Combined",
      score: "91.2%",
      date: "13 Aug 2026",
    },
  ];

  const downloadReport = (report) => {

    const content = `
SOLAR & WIND DEPLOYMENT INTELLIGENCE
=====================================

Report: ${report.title}
Location: ${report.location}
Energy Type: ${report.type}
Score: ${report.score}
Generated: ${report.date}

This is a preliminary renewable energy
analysis report generated by the platform.
`;

    const blob = new Blob(
      [content],
      { type: "text/plain" }
    );

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = url;

    link.download =
      `${report.title.replaceAll(" ", "_")}.txt`;

    document.body.appendChild(link);

    link.click();

    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  return (
    <div className="reports-page">

      {/* HEADER */}
      <header className="module-header">

        <button
          className="module-back-btn"
          onClick={onBack}
        >
          ← Dashboard
        </button>

        <div className="module-user">

          <div className="module-avatar">
            {user?.name?.charAt(0)?.toUpperCase() || "U"}
          </div>

          <div className="module-user-info">
            <strong>{user?.name || "User"}</strong>
            <span>{user?.email || ""}</span>
          </div>

        </div>

      </header>


      {/* TITLE */}
      <section className="reports-title">

        <div className="reports-icon">
          📄
        </div>

        <div>
          <h1>Reports</h1>

          <p>
            View and download your renewable energy analysis reports
          </p>
        </div>

      </section>


      {/* REPORTS */}
      <main className="reports-container">

        <section className="reports-card">

          <div className="reports-header">

            <div>
              <h2>Analysis Reports</h2>

              <p>
                Recent analysis results
              </p>
            </div>

            <span>
              {reports.length} Reports
            </span>

          </div>


          {reports.map((report) => (

            <div
              className="report-item"
              key={report.title}
            >

              <div className="report-icon">
                📄
              </div>


              <div className="report-info">

                <h3>
                  {report.title}
                </h3>

                <p>
                  {report.location}
                  {" • "}
                  {report.type}
                </p>

                <span>
                  Generated {report.date}
                </span>

              </div>


              <div className="report-score">
                {report.score}
              </div>


              <button
                className="download-btn"
                onClick={() => downloadReport(report)}
              >
                ↓ Download
              </button>

            </div>

          ))}

        </section>

      </main>

    </div>
  );
}

export default Reports;